### ISSUE TITLE
Failed to install TA-Lib after install Cython

### ISSUE THREAD

**Issue by gzcf** [mrjbq7/ta-lib#121]
```
pip install Cython
pip install numpy
pip install TA-Lib
```

It will throw
```
# The top few lines
Downloading/unpacking TA-Lib
  Downloading TA-Lib-0.4.10.tar.gz (829kB): 829kB downloaded
  Running setup.py (path:/root/tmp/.venv/build/TA-Lib/setup.py) egg_info for package TA-Lib
    
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cimport numpy as np
    from numpy import nan
    from cython import boundscheck, wraparound
    
    from .common cimport _ta_check_success
    ^
    ------------------------------------------------------------
    
    talib/stream.pyx:5:0: 'talib/common.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    cimport numpy as np
    from numpy import nan
    from cython import boundscheck, wraparound
    
    from .common cimport _ta_check_success
    ^
    ------------------------------------------------------------
    
    talib/stream.pyx:5:0: 'talib/common/_ta_check_success.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        int PyArray_FLAGS(np.ndarray)
        object PyArray_GETCONTIGUOUS(np.ndarray)
    
    np.import_array() # Initialize the NumPy C API
    
    cimport libta_lib as lib
           ^
    ------------------------------------------------------------
    
    talib/stream.pyx:17:8: 'libta_lib.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        object PyArray_GETCONTIGUOUS(np.ndarray)
    
    np.import_array() # Initialize the NumPy C API
    
    cimport libta_lib as lib
    from libta_lib cimport TA_RetCode
    ^
    ------------------------------------------------------------
    
    talib/stream.pyx:18:0: 'libta_lib/TA_RetCode.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cdef:
            np.npy_intp length
            double val
            int begidx, endidx, lookback
            TA_RetCode retCode
           ^
    ------------------------------------------------------------
    
    talib/stream.pyx:38:8: 'TA_RetCode' is not a type identifier

...
# Omit many many lines
...

# The last few lines
talib/stream.pyx:8072:106: Cannot convert 'double *' to Python object

talib/common.pyx: cannot find cimported module 'libta_lib'

talib/func.pyx: cannot find cimported module 'libta_lib'

talib/func.pyx: cannot find cimported module '.common'

talib/abstract.pyx: cannot find cimported module 'libta_lib'

talib/stream.pyx: cannot find cimported module 'libta_lib'

talib/stream.pyx: cannot find cimported module '.common'

Compiling talib/stream.pyx because it changed.

[1/1] Cythonizing talib/stream.pyx

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/root/tmp/.venv/build/TA-Lib/setup.py", line 122, in <module>

    requires = ['numpy'],

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 15, in replacement_run

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 186, in find_sources

    mm.run()

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 246, in run

    self.add_defaults()

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 282, in add_defaults

    sdist.add_defaults(self)

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/setuptools/command/sdist.py", line 179, in add_defaults

    build_ext = self.get_finalized_command('build_ext')

  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 19, in finalize_options

    self.distribution.ext_modules)

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 925, in cythonize

    cythonize_one(*args)

  File "/root/tmp/.venv/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1047, in cythonize_one

    raise CompileError(None, pyx_file)

Cython.Compiler.Errors.CompileError: talib/stream.pyx

----------------------------------------
Cleaning up...
```

Too many errors to paste them all.

If I **uninstall `Cython` before installing TA-Lib**, TA-LIb can be installed successfully.

Package version:

```
(.venv)x@y:z# pip list
argparse (1.2.1)
Cython (0.25)
numpy (1.11.2)
pip (1.5.4)
setuptools (2.2)
wsgiref (0.1.2)
```

Ubuntu 14.04.1 LTS

Any idea?

**Comment by mrjbq7** [comment]
That's odd - what version of Cytgon is it? And did you already have Cython via some ubuntu package before your pip install Cython?

**Comment by gzcf** [comment]
Cython version is 0.25. There isn't Cython before my pip install Cython. The way I check is:

```
>>> from Cython.Distutils import build_ext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Cython.Distutils
```

**Comment by gzcf** [comment]
After I installed Cython 0.24.1, I installed TA-Lib successfully. I found out Cython 0.25 is very new, it was released at 2016-10-25(refer [CHANGES](https://github.com/cython/cython/blob/master/CHANGES.rst)). Maybe it's a compatibility problem.

**Comment by bigtan** [comment]
@mrjbq7 incompatibility problem maybe solved througth https://github.com/mrjbq7/ta-lib/pull/124, please review.

**Comment by mrjbq7** [comment]
It seems to work with Cython 0.25.1.  Can you try that newer release?

**Comment by gzcf** [comment]
Yes, It can work with Cython 0.25.1.

**Comment by mrjbq7** [comment]
Weird, maybe they had some regression. Since its fixed maybe we don't make any changes, I guess.

**Comment by briancappello** [comment]
Couldn't find the changelog anywhere on the website, but it's in git and
for 0.25 says:
The distutils extension Cython.Distutils.build_ext has now been updated to
use cythonize which properly handles dependencies. The old extension can
still be found in Cython.Distutils.old_build_ext and is now deprecated.

0.25.1 reverts this change, but leaves the existing behavior deprecated:
The distutils extension Cython.Distutils.build_ext has been reverted,
temporarily, to be old_build_ext to give projects time to migrate. The new
build_ext is available as new_build_ext.

I couldn't find any migration guide, however.

On Fri, Oct 28, 2016 at 9:52 AM, John Benediktsson <notifications@github.com
