### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by AlexYang1949** [mrjbq7/ta-lib#147]
i use talib in pycharm ,import it no error ,but when run it  appear error:
Traceback (most recent call last):
  File "/Users/yangzhaoheng/Documents/python/python.py", line 3, in <module>
    from talib import abstract
  File "/Users/yangzhaoheng/Library/Python/2.7/lib/python/site-packages/talib/__init__.py", line 5, in <module>
    from . import abstract
  File "__init__.pxd", line 155, in init talib.abstract (talib/abstract.c:15127)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by mrjbq7** [comment]
That error is generated by the Cython bindings and maybe caused by having a 32-bit/64-bit mixed environment?

**Comment by newstarwind** [comment]
I met the same problem anyone could help?
