### ISSUE TITLE
Error when import on Linux

### ISSUE THREAD

**Issue by dominhtri1995** [mrjbq7/ta-lib#252]
Hi,

I have followed the steps on Readme and installed Ta-lib underlying library. I have also successfully installed this library through pip. 

However when I try to import talib , I get the following error:

```
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/.local/lib/python3.5/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
  File "__init__.pxd", line 163, in init talib._ta_lib
  File "/path/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/path/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 67, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy 
in ['/path/.local/lib/python3.5/site-packages/numpy']. One method of fixing this is to repeatedly unins
tall numpy until none is found, then reinstall this version.
```

I'm using python 3.5.3 . Numpy: 1.16.1 (latest) . OS: Linux google compute engine.

Plz help.

**Comment by dominhtri1995** [comment]
Use pip uninstall numpy alone won't work. I need to remove manually '/path/.local/lib/python3.5/site-packages/numpy' and then pip uninstall numpy. Then pip install numpy again.

Thanks
