### ISSUE TITLE
NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by anoopky** [mrjbq7/ta-lib#278]
```
▶ pip3 install ta-lib
Collecting ta-lib
  Using cached https://files.pythonhosted.org/packages/90/05/d4c6a778d7a7de0be366bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sbolg1oi/ta-lib/setup.py", line 128, in <module>
        **requires
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 226, in __init__
        if isinstance(self.metadata.version, (int,long,float)):
    NameError: name 'long' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sbolg1oi/ta-lib/

```

**Comment by mrjbq7** [comment]
That error looks like it comes from setuptools, not ta-lib. Perhaps try updating your installation of setuptools/pip/distutils first.
