### ISSUE TITLE
 raise AssertionError("build_ext overridden!") when call python setup.py install

### ISSUE THREAD

**Issue by gekator** [mrjbq7/ta-lib#344]
I use Ubuntu 64bit 19.04. I use python 3.7.5
I installed the TA-LIB libraries from  ta-lib-0.4.0-src.tar.gz successfully. 
However when i call python setup.py install i get that error:

running install
running build
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    **requires)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
    self.run_command('build')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 983, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 857, in get_command_obj
    klass = self.get_command_class(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 840, in get_command_class
    self.cmdclass[command] = klass
  File "setup.py", line 86, in __setitem__
    raise AssertionError("build_ext overridden!")
AssertionError: build_ext overridden!

What should i do?

**Comment by mrjbq7** [comment]
I'm not sure what is different about your ``distutils`` that seems to be overriding the ``build_ext`` that is provided in the ``setup.py``... that does not happen with my Python3 installations.

**Comment by yipikaye** [comment]
Any resolution to this? I have the same issue.

**Comment by mrjbq7** [comment]
Can you provide some information about your environment?  What version of python, cython, numpy, distutils, setuputils?

**Comment by Twister7** [comment]
same issue on aarch64 AWS serve. Python 3.7.3

**Comment by mrjbq7** [comment]
Could be fixed by f1e4a502f8c4f3116a0ddf4e16f7c9aa7f51e525 as part of the pep-517 style installation.
