### ISSUE TITLE
Unable to install in aarch64 with python 3.8

### ISSUE THREAD

**Issue by arunbv123** [mrjbq7/ta-lib#392]
I have successfully installed ta-lib code from source, but unable to install python wrapper.

Command:
pip3 install -e . --verbose

error:
Using pip 20.3.3 from /data/pyenv/stocksv2/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-sfijr3us
Created temporary directory: /tmp/pip-req-tracker-lrj45egu
Initialized build tracking at /tmp/pip-req-tracker-lrj45egu
Created build tracker: /tmp/pip-req-tracker-lrj45egu
Entered build tracker: /tmp/pip-req-tracker-lrj45egu
Created temporary directory: /tmp/pip-install-ht6j_uuv
Obtaining file:///data/builds/ta-lib
  Added file:///data/builds/ta-lib to build tracker '/tmp/pip-req-tracker-lrj45egu'
    Running setup.py (path:/data/builds/ta-lib/setup.py) egg_info for package from file:///data/builds/ta-lib
    Created temporary directory: /tmp/pip-pip-egg-info-sor8yvw3
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-sor8yvw3/TA_Lib.egg-info
    writing /tmp/pip-pip-egg-info-sor8yvw3/TA_Lib.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-sor8yvw3/TA_Lib.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-sor8yvw3/TA_Lib.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-sor8yvw3/TA_Lib.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-sor8yvw3/TA_Lib.egg-info/SOURCES.txt'
ERROR: Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 346, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 575, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/data/pyenv/stocksv2/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status -4: python setup.py egg_info Check the logs for full command output.

**Comment by mrjbq7** [comment]
What is the output it refers to?

python setup.py egg_info

**Comment by ppkantorski** [comment]
i too am having issues.  brew can install it, but pip3 via conda over miniforge3 cannot.

**Comment by mrjbq7** [comment]
Most issues are mixing architecture. And mixing homebrew locations.  I can look into specific issues when I have time later.

**Comment by mrjbq7** [comment]
If using pip, there is an unreleased patch to add /opt/homebrew as a location to search for ta-lib dylib library.

Try using git master and Python setup.py install. 

Also, you might need to “brew link ta-lib” so it’s linked in /opt/homebrew/lib rather than somewhere like /opt/homebrew/opt/ta-lib

**Comment by ppkantorski** [comment]
My homebrew is installed in /opt/homebrew for arm64 while conda is in the miniforge3 folder.  is it possible to link ta-lib from homebrew with my arm64 python build from conda?

**Comment by arunbv123** [comment]
python setup.py egg_info is something internally python is doing. I even tried running make file, it also throws a error.

My environment info: Linux arun-jetson 4.9.140-tegra #1 SMP PREEMPT Tue Oct 27 21:02:37 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by wwwjinlong** [comment]
ARCHFLAGS="-arch x86_64" pip install  quickfix

**Comment by arunbv123** [comment]
I was able to get this working once I upgraded to ubuntu 20.04. Thanks for all the support :)
