### ISSUE TITLE
can not compile ta-lib with Nuitka

### ISSUE THREAD

**Issue by jonozw** [mrjbq7/ta-lib#413]
1. Compile binary with Nuitka
2. Run the binary, it show error: 

(talib) X:\stock\code\tastock\tusc.dist>tusc.exe
Traceback (most recent call last):
  File "X:\stock\code\tastock\tusc.dist\tusc.py", line 3, in <module>
  File "X:\stock\code\tastock\tusc.dist\talib\__init__.py", line 72, in <module talib>
ModuleNotFoundError: No module named 'talib.stream'

**Comment by mrjbq7** [comment]
I have never tested with that. 

Can you provide some instructions on how to compile the Cython bindings using Nuitka?

Thanks,

**Comment by jonozw** [comment]
The instruction  to compile python with cython using Nuitka is

```
nuitka --standalone --plugin-enable=numpy --plugin-enable=pylint-warnings --windows-disable-console hello.py
```

The compilation was completed without  problem. 

It is runtime error. "ModuleNotFoundError: No module named 'talib.stream'"

line 72: stream = __import__("stream", globals(), locals(), stream_func_names, level=1)

Nuitka's repo is: https://github.com/Nuitka/Nuitka

**Comment by rwayan** [comment]
Same Problem Here
