### ISSUE TITLE
already install but still error

### ISSUE THREAD

**Issue by Easyzhan** [mrjbq7/ta-lib#512]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'talib'

**Comment by trufanov-nok** [comment]
could you provide us with more details?

**Comment by Easyzhan** [comment]
macox，i had install，but can't use it,
<img width="244" alt="image" src="https://user-images.githubusercontent.com/8928783/163378432-71dbc4b2-5d20-49cb-b6e2-f88ddf16886e.png">

when run in pycharm:

  import talib
  File "/Users/natsu/Music/coinphilosophy/venv/lib/python3.9/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

when debug :
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/natsu/Music/coinphilosophy/venv/lib/python3.9/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by trufanov-nok** [comment]
Try
```
sudo pip uninstall ta-lib
sudo pip cache remove TA_Lib-*
sudo pip install ta-lib
```
This should rebuild the wrapper with currently installed numpy 1.22.3 ignoring the cached wheels which seems to be build with older numpy version.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
