### ISSUE TITLE
no attribute 'abstract' error

### ISSUE THREAD

**Issue by lkthomas** [mrjbq7/ta-lib#79]
Traceback (most recent call last):
  File "/home/tlau/eclipse_workspace/Thomas_Python/Self-project/talib.py", line 2, in <module>
    import talib
  File "/home/tlau/eclipse_workspace/Thomas_Python/Self-project/talib.py", line 5, in <module>
    output = talib.abstract.SMA(close)
AttributeError: 'module' object has no attribute 'abstract'

code:

import numpy
import talib

close = numpy.random.random(100)
output = talib.abstract.SMA(close)

Any idea why? talib code compiled and TA-lib python module installed without problem.

**Comment by lkthomas** [comment]
found the problem, your project file name can't be talib.py AND talib.pyc should not be exists on project directory.
