### ISSUE TITLE
Linux: dynamic module does not define init function

### ISSUE THREAD

**Issue by fpemud** [mrjbq7/ta-lib#96]
```
fpemud-workstation / # python3
Python 3.3.5 (default, Dec 28 2015, 14:33:21) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.3/site-packages/talib/__init__.py", line 5, in <module>
    from . import abstract
ImportError: dynamic module does not define init function (PyInit_abstract)
```

**Comment by mrjbq7** [comment]
Fixed now I think, try updating to latest?
